#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct.
set -xe
VERSION="$(cat VERSION | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
DOCKERFILE=Dockerfile
DOCKER_UPSTREAM="https://raw.githubusercontent.com/docker-library/docker/a6b52c73daa8283cd861f41f55e53426008708ac/17.09/Dockerfile"

curl -sSl "${DOCKER_UPSTREAM}" |  sed  '0,/^FROM.*$/ d' | sed '/^COPY docker-entrypoint.*/,$ d' > dockerinfo.tmp

cat dockerinfo.tmp

perl -pe 's/<INSERT_DOCKER_MAKE_HERE>/`cat dockerinfo.tmp`/ge' ${DOCKERFILE} > Dockerfile.out



docker build \
    --build-arg VCS_REF=$(git rev-parse --short HEAD) \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VERSION="$VERSION" \
    -t $IMAGE_NAME -f Dockerfile.out .
