#!/bin/bash
# $IMAGE_NAME var is injected into the build so the tag is correct.
set -xe
VERSION="$(cat VERSION | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
DOCKERFILE=Dockerfile
DOCKER_VERSION=17.06

curl -sSl "https://raw.githubusercontent.com/docker-library/docker/master/${DOCKER_VERSION}/Dockerfile" |  sed  '0,/^FROM.*$/ d' | sed '/^COPY docker-entrypoint.*/,$ d' > dockerinfo.tmp

DOCKER_DATA=$(perl -pe 's/<INSERT_DOCKER_MAKE_HERE>/`cat dockerinfo.tmp`/ge' ${DOCKERFILE})

echo "$DOCKER_DATA" | docker build \
    --build-arg VCS_REF=$(git rev-parse --short HEAD) \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VERSION="$VERSION" \
    -t $IMAGE_NAME
